/**
 * Regenerates the static aviation reference datasets in `src/*.generated.ts`.
 *
 * Source: OpenFlights (https://github.com/jpatokal/openflights) public datasets.
 * Run with:  bun run common/data/scripts/build-data.ts
 *
 * The raw `.dat` files are OpenFlights' pipe-delimited format with a documented
 * column order and a literal `\N` for "unknown". We only keep the fields this
 * app actually needs and drop anything without a usable code.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const srcDir = join(here, "..", "src");
const rawDir = join(here, "..", "raw");

const UNKNOWN = "\\N";

/** OpenFlights ships comma-delimited values with quoted fields (city names can
 * contain commas, e.g. `Washington, D.C.`), so a naive split is wrong. */
function splitCsvLine(line: string): string[] {
  const out: string[] = [];
  let cur = "";
  let quoted = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i]!;
    if (quoted) {
      if (ch === '"' && line[i + 1] === '"') {
        cur += '"';
        i++;
      } else if (ch === '"') {
        quoted = false;
      } else {
        cur += ch;
      }
    } else if (ch === '"') {
      quoted = true;
    } else if (ch === ",") {
      out.push(cur);
      cur = "";
    } else {
      cur += ch;
    }
  }
  out.push(cur);
  return out;
}

function readDat(file: string): string[][] {
  return readFileSync(join(rawDir, file), "utf8")
    .split("\n")
    .filter((line) => line.trim().length > 0)
    .map(splitCsvLine);
}

const HEADER = `// AUTO-GENERATED by common/data/scripts/build-data.ts — do not edit by hand.
// Source: OpenFlights (https://github.com/jpatokal/openflights), public dataset.
`;

// ---------------------------------------------------------------- airports
// Columns: 0 id, 1 name, 2 city, 3 country, 4 iata, 5 icao, 6 lat, 7 lon,
//          8 alt, 9 tz, 10 dst, 11 tzdb, 12 type, 13 source
type Airport = {
  iata: string;
  icao: string | null;
  name: string;
  city: string;
  country: string;
  lat: number;
  lon: number;
  elevationFt: number;
  timezone: string;
  type: string;
};

const airports: Airport[] = [];
for (const cols of readDat("airports.dat")) {
  const [, name, city, country, iata, icao, lat, lon, alt, tz, , , type] = cols;
  if (!iata || iata === UNKNOWN) continue; // we key everything on IATA
  const latNum = Number(lat);
  const lonNum = Number(lon);
  if (!Number.isFinite(latNum) || !Number.isFinite(lonNum)) continue;
  airports.push({
    iata: iata.trim(),
    icao: icao && icao !== UNKNOWN ? icao.trim() : null,
    name: name.trim().replace(/\s+/g, " "),
    city: city.trim().replace(/\s+/g, " "),
    country: country.trim(),
    lat: latNum,
    lon: lonNum,
    elevationFt: alt && alt !== UNKNOWN ? Number(alt) || 0 : 0,
    timezone: tz && tz !== UNKNOWN ? tz.trim() : "UTC",
    type: type.trim(),
  });
}
airports.sort((a, b) => a.iata.localeCompare(b.iata));

// ---------------------------------------------------------------- airlines
// Columns: 0 id, 1 name, 2 alias, 3 iata, 4 icao, 5 callsign, 6 country, 7 active
type Airline = {
  iata: string | null;
  icao: string | null;
  name: string;
  callsign: string | null;
  country: string;
  active: boolean;
};

const airlines: Airline[] = [];
for (const cols of readDat("airlines.dat")) {
  // The alias column is unused; the name alone is what the resolver ranks on.
  const [, name, , iata, icao, callsign, country, active] = cols;
  const hasIata = iata && iata !== UNKNOWN;
  const hasIcao = icao && icao !== UNKNOWN;
  if (!hasIata && !hasIcao) continue;
  airlines.push({
    iata: hasIata ? iata.trim() : null,
    icao: hasIcao ? icao.trim() : null,
    name: name.trim().replace(/\s+/g, " "),
    callsign: callsign && callsign !== UNKNOWN ? callsign.trim() : null,
    country: country && country !== UNKNOWN ? country.trim() : "",
    active: active === "Y",
  });
}
airlines.sort((a, b) => a.name.localeCompare(b.name));

// ------------------------------------------------------------------ routes
// Columns: 0 airline, 1 airline_id, 2 source, 3 source_id, 4 dest, 5 dest_id,
//          6 codeshare, 7 stops, 8 equipment, 9 codeshare_id
// Only fields we use: airline IATA, source IATA, dest IATA.
//
// Codeshare rows are counted but not emitted as their own route: they
// duplicate the operating carrier. Counting them anyway is the whole point —
// it turns a list of "this route exists" into a rough popularity signal, which
// is what lets the resolver rank "which of these did they mean?".
const routeCounts = new Map<string, number>();
for (const cols of readDat("routes.dat")) {
  const [airline, , src, , dest] = cols as [
    string,
    string,
    string,
    string,
    string,
    ...string[],
  ];
  if (!airline || airline === UNKNOWN || !src || !dest) continue;
  if (src === dest) continue;
  const key = `${airline.trim()}|${src.trim()}|${dest.trim()}`;
  routeCounts.set(key, (routeCounts.get(key) ?? 0) + 1);
}

const routeRows = [...routeCounts.entries()]
  .map(([key, count]) => {
    const [airline, src, dest] = key.split("|");
    return { airline: airline!, src: src!, dest: dest!, count };
  })
  .sort((a, b) => b.count - a.count || a.airline.localeCompare(b.airline));

const airportIatas = new Set(airports.map((a) => a.iata));
const validRoutes = routeRows.filter((r) => airportIatas.has(r.src) && airportIatas.has(r.dest));

type RouteRow = { airline: string; src: string; dest: string; count: number };

function packRoutes(rows: RouteRow[]): string {
  return rows.map((r) => `${r.airline}|${r.src}|${r.dest}:${r.count}`).join(";");
}

// ------------------------------------------------------------------ emit
mkdirSync(srcDir, { recursive: true });

/**
 * How many scheduled routes touch each airport.
 *
 * OpenFlights has no airport-size column — every row is just `airport` — so
 * this is the best available proxy for "is this a real hub?". It does double
 * duty: it ranks the airports behind an ambiguous city name (London is five
 * airports, and LHR should win), and it filters out the heliports and seaplane
 * bases that would otherwise show up as legitimate destinations.
 */
const hubRoutes = new Map<string, number>();
for (const key of routeCounts.keys()) {
  const [, src, dest] = key.split("|");
  for (const code of [src!, dest!]) hubRoutes.set(code, (hubRoutes.get(code) ?? 0) + 1);
}

const withRoutes = airports
  .map((a) => ({ ...a, routes: hubRoutes.get(a.iata) ?? 0 }))
  .sort((a, b) => a.iata.localeCompare(b.iata));

/**
 * Same idea for carriers. Without it, "United" resolves to United Airways and
 * "Delta" to Delta Aerotaxi, because those names also start with the word the
 * user typed. Route count is the discriminator.
 */
const airlineRouteCounts = new Map<string, number>();
for (const key of routeCounts.keys()) {
  const [airline] = key.split("|");
  airlineRouteCounts.set(airline!, (airlineRouteCounts.get(airline!) ?? 0) + 1);
}

const airlinesWithRoutes = airlines
  .map((a) => {
    const code = a.iata ?? a.icao;
    return { ...a, routes: code ? (airlineRouteCounts.get(code) ?? 0) : 0 };
  })
  .sort((a, b) => a.name.localeCompare(b.name));

const banner = (s: string) => `${HEADER}\nexport ${s}\n`;

writeFileSync(
  join(srcDir, "airports.generated.ts"),
  `${banner(`const AIRPORTS: Airport[] = ${JSON.stringify(withRoutes)};`)}
export type Airport = {
  iata: string;
  icao: string | null;
  name: string;
  city: string;
  country: string;
  lat: number;
  lon: number;
  elevationFt: number;
  timezone: string;
  type: string;
  /** Number of scheduled routes touching this airport; 0 for heliports etc. */
  routes: number;
};
export const airports: readonly Airport[] = AIRPORTS;
`,
);

writeFileSync(
  join(srcDir, "airlines.generated.ts"),
  `${banner(`const AIRLINES: Airline[] = ${JSON.stringify(airlinesWithRoutes)};`)}
export type Airline = {
  iata: string | null;
  icao: string | null;
  name: string;
  callsign: string | null;
  country: string;
  active: boolean;
  /** Approximate number of known routes; 0 for defunct and cargo-only carriers. */
  routes: number;
};
export const airlines: readonly Airline[] = AIRLINES;
`,
);

writeFileSync(
  join(srcDir, "routes.generated.ts"),
  `${banner(`const ROUTE_PACK: string = ${JSON.stringify(packRoutes(validRoutes))};`)}
export type RouteRow = { airline: string; src: string; dest: string; count: number };

/**
 * Every known non-codeshare route, busiest first, packed as one string of
 * \`AIRLINE|SRC|DEST:COUNT\` records separated by \`;\`.
 *
 * Stored packed rather than as an array of objects because the raw form is
 * ~4x larger and this table is imported by the backend on every deploy. \`count\`
 * is a rough popularity signal, not a real frequency.
 * Server-side use only — it is deliberately not re-exported from index.ts so
 * it stays out of the browser bundle.
 */
export const routeRows: readonly RouteRow[] = parseRoutePack(ROUTE_PACK);

function parseRoutePack(pack: string): RouteRow[] {
  const out: RouteRow[] = [];
  for (const record of pack.split(";")) {
    if (!record) continue;
    const [keys, count] = record.split(":");
    const [airline, src, dest] = keys!.split("|");
    out.push({ airline: airline!, src: src!, dest: dest!, count: Number(count) });
  }
  return out;
}
`,
);  console.log(
    `airports=${withRoutes.length} airlines=${airlines.length} routes=${validRoutes.length} (from ${routeCounts.size} raw)`,
  );
